<?php
if(isset($_POST['login'])){
    $user=$_POST['user'];
    $pass=$_POST['password'];
}
if(isset($_POST['registro'])){
    $user=$_POST['user'];
    $pass=$_POST['password'];
    $pass=$_POST['email'];
}
?>